name: 'web-ext lint'
description: 'Lint WebExtension with annotations'
branding:
  icon: 'check'
  color: 'green'
inputs:
  extension-root:
    description: 'Root folder of the extension that contains the manifest.json'
    required: false
    default: '.'
  verbose:
    description: 'When enabled, the description of all linter messages are also printed'
    required: false
    default: false
  self-hosted:
    description: 'Enable to indicate the extension will be self hosted'
    required: false
    default: false
  privileged:
    description: 'Enable to treat the extension as a privileged extension'
    required: false
    default: false
runs:
  using: 'node24'
  main: 'index.js'
